-- # Listo

CREATE DATABASE IF NOT EXISTS ProyectoFin;

USE ProyectoFin;

CREATE TABLE IF NOT EXISTS tickets (
    id INT AUTO_INCREMENT PRIMARY KEY,
    usuario TEXT NOT NULL,
    falla TEXT NOT NULL,
    fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    solucionado BOOLEAN DEFAULT FALSE
);

